export const PROJECT_NAME = "Magic Sanguo";

export function getLogicTicksPerSecond(): number {
  return 60;
}

export * from "./model/index.js";
export * from "./combat/CombatEngine.js";
export * from "./combat/CombatResultSummaryBuilder.js";
export * from "./combat/DamageCalculator.js";
export * from "./combat/ResolutionStack.js";
export * from "./combat/commands/CombatCommand.js";
export * from "./combat/commands/ApplyBurnCommand.js";
export * from "./combat/commands/ApplyControlStatusCommand.js";
export * from "./combat/commands/ApplyFreezeCommand.js";
export * from "./combat/commands/ApplyHasteCommand.js";
export * from "./combat/commands/ApplyPoisonCommand.js";
export * from "./combat/commands/ApplySlowCommand.js";
export * from "./combat/commands/DealDamageCommand.js";
export * from "./combat/commands/GainArmorCommand.js";
export * from "./combat/commands/HealHPCommand.js";
export * from "./combat/commands/ModifyCooldownCommand.js";
export * from "./combat/status/Burn.js";
export * from "./combat/status/ControlStatus.js";
export * from "./combat/status/Poison.js";
export * from "./combat/status/StatusEffect.js";
export * from "./combat/status/StatusEffectSystem.js";
export * from "./combat/modifiers/Modifier.js";
export * from "./combat/modifiers/ModifierHooks.js";
export * from "./combat/modifiers/ModifierSystem.js";
export * from "./combat/triggers/TriggerDefinition.js";
export * from "./combat/triggers/TriggerRuntimeState.js";
export * from "./combat/triggers/TriggerSystem.js";
export * from "./content/cards/effectiveCardDefinition.js";
export * from "./content/cards/activeCards.js";
export * from "./content/cards/contentPools.js";
export * from "./content/cards/monsterCards.js";
export * from "./content/enchantments/enchantments.js";
export * from "./content/enchantments/enchantmentTargets.js";
export * from "./content/monsters/MonsterGenerator.js";
export * from "./content/monsters/MonsterTemplate.js";
export * from "./content/monsters/monsterTemplates.js";
export * from "./content/rewards/rewardCards.js";
export * from "./debug/sampleCombatReplayExport.js";
export * from "./replay/ReplayEvent.js";
export * from "./replay/ReplayTimeline.js";
export * from "./replay/time.js";
export * from "./run/RunManager.js";
export * from "./run/RunState.js";
export * from "./run/nodes/BattleNode.js";
export * from "./run/nodes/EventGenerator.js";
export * from "./run/nodes/EventNode.js";
export * from "./run/nodes/ShopNode.js";
export * from "./run/rewards/RewardGenerator.js";
export * from "./run/save/SaveManager.js";
export * from "./run/skills/Skill.js";
export * from "./run/skills/skillDefinitions.js";
export * from "./validation/cardValidation.js";
export * from "./validation/enchantmentValidation.js";
export * from "./validation/formationValidation.js";
export * from "./validation/rewardCardValidation.js";
export * from "./validation/validationResult.js";
